"""Polished Telegram Mini App game hub."""

GAME_PAGE = r"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,user-scalable=no"><meta name="theme-color" content="#090b14">
<title>STARBOOX</title><script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
:root{color-scheme:dark;--bg:#080a12;--panel:#121522;--line:rgba(255,255,255,.08);--muted:#9199ae;--purple:#8b5cf6;--pink:#ec4899;--cyan:#22d3ee;--gold:#fbbf24;--green:#34d399;--safe:env(safe-area-inset-bottom,0px)}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{margin:0;min-height:100%;background:var(--bg);color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{background:radial-gradient(700px 420px at 80% -10%,rgba(139,92,246,.28),transparent 62%),radial-gradient(500px 360px at -10% 30%,rgba(34,211,238,.11),transparent 60%),var(--bg)}button{font:inherit}.app{max-width:520px;margin:auto;padding:14px 14px calc(98px + var(--safe));overflow:hidden}.top{display:flex;justify-content:space-between;align-items:center;padding:5px 2px 15px}.brand{font-size:18px;font-weight:950;letter-spacing:.05em}.brand i{font-style:normal;color:var(--gold);filter:drop-shadow(0 0 10px rgba(251,191,36,.55))}.avatar{width:40px;height:40px;border-radius:14px;background:linear-gradient(135deg,var(--purple),var(--pink));display:grid;place-items:center;font-weight:900;box-shadow:0 8px 24px rgba(139,92,246,.28)}
.hero,.panel{position:relative;border:1px solid var(--line);background:linear-gradient(145deg,rgba(25,29,47,.96),rgba(14,17,29,.96));border-radius:25px;box-shadow:0 18px 55px rgba(0,0,0,.24);overflow:hidden}.hero{padding:19px;margin-bottom:13px}.hero:after{content:"";position:absolute;width:170px;height:170px;right:-70px;top:-90px;border-radius:50%;background:var(--purple);filter:blur(52px);opacity:.3;pointer-events:none}.eyebrow{color:var(--muted);font-size:11px;font-weight:750;letter-spacing:.08em}.user-name{font-weight:900;font-size:20px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.level{display:flex;align-items:center;gap:9px;margin-top:13px}.level-track{height:7px;flex:1;background:#ffffff0b;border-radius:20px;overflow:hidden}.level-fill{width:0;height:100%;background:linear-gradient(90deg,var(--purple),var(--cyan));border-radius:inherit;transition:width .7s ease}.level small{font-size:10px;color:var(--muted)}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:15px}.stat{border:1px solid #ffffff0a;background:#ffffff08;border-radius:16px;padding:11px 7px;text-align:center;transition:transform .2s}.stat:active{transform:scale(.96)}.stat b{display:block;font-size:14px}.stat small{display:block;color:var(--muted);font-size:8px;font-weight:800;letter-spacing:.1em;margin-top:4px}.quick{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.soft-btn,.main-btn,.buy-btn{border:0;cursor:pointer;color:#fff;font-weight:850}.soft-btn{padding:11px;border-radius:14px;background:#ffffff0a;border:1px solid var(--line)}
.panel{padding:17px;margin-bottom:13px}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.section-title{font-weight:950;font-size:14px;letter-spacing:.08em}.badge{font-size:10px;font-weight:850;color:#d8ccff;background:rgba(139,92,246,.15);border:1px solid rgba(139,92,246,.24);border-radius:20px;padding:6px 9px}
.wheel-stage{position:relative;width:282px;height:282px;margin:7px auto 14px;display:grid;place-items:center}.wheel-glow{position:absolute;inset:19px;border-radius:50%;background:var(--purple);filter:blur(28px);opacity:.2}.pointer{position:absolute;z-index:5;top:-2px;width:0;height:0;border-left:15px solid transparent;border-right:15px solid transparent;border-top:30px solid #fff;filter:drop-shadow(0 4px 7px #000);transform-origin:50% 3px}.wheel{position:relative;width:248px;height:248px;border-radius:50%;background:conic-gradient(from -22.5deg,#7c3aed 0 45deg,#0ea5e9 45deg 90deg,#ec4899 90deg 135deg,#f59e0b 135deg 180deg,#10b981 180deg 225deg,#6366f1 225deg 270deg,#ef4444 270deg 315deg,#14b8a6 315deg 360deg);border:8px solid #252a40;box-shadow:inset 0 0 0 4px #ffffff14,0 15px 35px #0008;transition:transform 3.4s cubic-bezier(.12,.68,.12,1)}.wheel:before{content:"";position:absolute;inset:10px;border-radius:50%;background:repeating-conic-gradient(from 0deg,transparent 0 44deg,#ffffff35 44deg 45deg)}.wheel-center{position:absolute;z-index:3;width:68px;height:68px;border-radius:50%;display:grid;place-items:center;font-size:30px;background:linear-gradient(145deg,#fff,#bfc5d5);box-shadow:0 8px 22px #0009;color:#141726;border:6px solid #343a53}.main-btn{position:relative;width:100%;padding:15px;border-radius:16px;background:linear-gradient(100deg,#7c3aed,#a855f7,#ec4899);background-size:180% 100%;box-shadow:0 10px 26px rgba(139,92,246,.28);letter-spacing:.04em;transition:transform .16s,filter .16s}.main-btn:active{transform:scale(.975)}.main-btn:disabled{filter:grayscale(.7);opacity:.55}.main-btn:not(:disabled):after{content:"";position:absolute;inset:0;border-radius:inherit;background:linear-gradient(105deg,transparent 35%,#fff5 50%,transparent 65%);transform:translateX(-130%);animation:shine 3s infinite}@keyframes shine{55%,100%{transform:translateX(130%)}}
.cases{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.case{position:relative;text-align:center;padding:15px 10px 11px;border-radius:20px;background:linear-gradient(150deg,#ffffff0d,#ffffff04);border:1px solid var(--line);overflow:hidden;transition:transform .2s,border-color .2s}.case:active{transform:scale(.975)}.case.featured{grid-column:1/-1;display:grid;grid-template-columns:80px 1fr;align-items:center;text-align:left;background:linear-gradient(120deg,rgba(251,191,36,.14),rgba(139,92,246,.12));border-color:rgba(251,191,36,.24)}.case-icon{font-size:47px;filter:drop-shadow(0 8px 13px rgba(139,92,246,.4));animation:float 3s ease-in-out infinite}.case.featured .case-icon{font-size:55px;text-align:center}.case-name{font-size:12px;font-weight:900;margin:6px 0 3px}.case-desc{font-size:9px;color:var(--muted);margin-bottom:8px}.case-actions{display:flex;flex-direction:column;gap:5px}.buy-btn{width:100%;border-radius:11px;padding:9px 5px;font-size:10px;background:#ffffff10;border:1px solid var(--line)}.buy-btn.primary{background:linear-gradient(90deg,#7652e8,#9e5cf5);border:0}.buy-btn.free{background:linear-gradient(90deg,#d99a0b,#f3bd35);color:#201600;border:0}@keyframes float{50%{transform:translateY(-5px) rotate(2deg)}}
.store{display:flex;gap:9px;overflow-x:auto;scroll-snap-type:x mandatory;padding:2px 1px 5px;scrollbar-width:none}.store::-webkit-scrollbar{display:none}.product{min-width:145px;scroll-snap-align:start;border:1px solid var(--line);background:#ffffff08;border-radius:18px;padding:14px;text-align:center}.product .emoji{font-size:31px}.product b{display:block;font-size:12px;margin:6px 0}.product span{display:block;color:var(--muted);font-size:9px;margin-bottom:9px}.product button{width:100%;border:0;border-radius:11px;padding:9px;background:linear-gradient(90deg,#ec4899,#8b5cf6);color:#fff;font-weight:900;font-size:10px}
.overlay{position:fixed;z-index:50;inset:0;background:#05060bd9;backdrop-filter:blur(12px);display:none;align-items:center;justify-content:center;padding:22px}.overlay.show{display:flex;animation:fade .2s}.prize{width:min(360px,100%);text-align:center;background:linear-gradient(145deg,#1d2134,#10131f);border:1px solid #ffffff17;border-radius:28px;padding:27px 20px;animation:pop .38s cubic-bezier(.2,1.4,.3,1)}.prize-icon{font-size:74px;filter:drop-shadow(0 10px 25px rgba(251,191,36,.35))}.prize h2{margin:7px 0 5px;font-size:23px}.prize p{margin:0 0 18px;color:var(--muted)}.toast{position:fixed;z-index:80;left:16px;right:16px;bottom:calc(18px + var(--safe));max-width:488px;margin:auto;padding:13px 15px;background:#272c41eF;border:1px solid #ffffff18;box-shadow:0 12px 30px #0008;border-radius:15px;text-align:center;font-size:12px;font-weight:750;opacity:0;transform:translateY(25px);pointer-events:none;transition:.25s}.toast.show{opacity:1;transform:none}.skeleton{height:14px;width:150px;border-radius:8px;background:linear-gradient(90deg,#ffffff08,#ffffff18,#ffffff08);background-size:200%;animation:load 1.2s infinite}@keyframes load{to{background-position:-200%}}@keyframes pop{from{transform:scale(.78);opacity:0}}@keyframes fade{from{opacity:0}}.confetti{position:fixed;z-index:70;width:8px;height:13px;top:-20px;animation:fall 1.8s linear forwards}@keyframes fall{to{transform:translate(var(--x),105vh) rotate(760deg)}}
</style></head><body><main class="app">
<header class="top"><div class="brand"><i>★</i> STARBOOX</div><div class="avatar" id="avatar">S</div></header>
<section class="hero"><div class="eyebrow">ДОБРО ПОЖАЛОВАТЬ</div><div class="user-name skeleton" id="name"></div><div class="level"><div class="level-track"><div class="level-fill" id="levelFill"></div></div><small id="level">LVL 1</small></div><div class="stats"><div class="stat"><b id="balance">—</b><small>БАЛАНС</small></div><div class="stat"><b id="keys">—</b><small>КЛЮЧИ</small></div><div class="stat"><b id="spins">—</b><small>СПИНЫ</small></div></div><div class="quick"><button class="soft-btn" onclick="share()">🤝 Пригласить</button><button class="soft-btn" onclick="reloadProfile()">↻ Обновить</button></div></section>
<section class="panel"><div class="section-head"><div class="section-title">🎡 РУЛЕТКА</div><div class="badge" id="spinBadge">0 спинов</div></div><div class="wheel-stage"><div class="wheel-glow"></div><div class="pointer"></div><div class="wheel" id="wheel"></div><div class="wheel-center">★</div></div><button class="main-btn" id="spinBtn" onclick="spinWheel()">КРУТИТЬ РУЛЕТКУ</button></section>
<section class="panel"><div class="section-head"><div class="section-title">🧰 КЕЙСЫ</div><div class="badge">до 100 ⭐</div></div><div class="cases" id="cases"><div class="case featured"><div class="case-icon">⏳</div><div><div class="skeleton"></div></div></div></div></section>
<section class="panel"><div class="section-head"><div class="section-title">🛍 МАГАЗИН</div><div class="badge">Telegram XTR</div></div><div class="store"><div class="product"><div class="emoji">🗝</div><b>5 ключей</b><span>Для платных кейсов</span><button onclick="buy('keys_5')">15 XTR</button></div><div class="product"><div class="emoji">🔑</div><b>15 ключей</b><span>Выгодный набор</span><button onclick="buy('keys_15')">39 XTR</button></div><div class="product"><div class="emoji">💎</div><b>VIP · 30 дней</b><span>Особый статус</span><button onclick="buy('vip_30')">99 XTR</button></div></div></section>
</main><div class="overlay" id="overlay" onclick="closePrize()"><div class="prize" onclick="event.stopPropagation()"><div class="prize-icon" id="prizeIcon">⭐</div><h2 id="prizeTitle">Ваш выигрыш</h2><p id="prizeText"></p><button class="main-btn" onclick="closePrize()">ЗАБРАТЬ</button></div></div><div class="toast" id="toast"></div>
<script>
const tg=window.Telegram&&window.Telegram.WebApp;const $=id=>document.getElementById(id);let profile=null,rotation=0,toastTimer,gameBusy=false;if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#090b14');tg.setBackgroundColor('#080a12')}catch(e){}}
function initData(){if(tg?.initData)return tg.initData;const q=new URLSearchParams(location.search),h=new URLSearchParams(location.hash.replace(/^#/,''));return q.get('tgWebAppData')||h.get('tgWebAppData')||''}
function haptic(type='impact'){try{type==='success'?tg?.HapticFeedback?.notificationOccurred('success'):tg?.HapticFeedback?.impactOccurred(type==='light'?'light':'medium')}catch(e){}}
function toast(text){clearTimeout(toastTimer);const e=$('toast');e.textContent=text;e.classList.add('show');toastTimer=setTimeout(()=>e.classList.remove('show'),3000)}
function requestId(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
async function api(path,data={}){const auth=initData();if(!auth)throw Error('Откройте Mini App кнопкой в личном чате с ботом');const r=await fetch(path,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,initData:auth})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Ошибка сервера');return j}
function rewardLabel(r){return r.kind==='stars'?`${r.amount} ⭐`:r.kind==='key'?`${r.amount} ключ`:r.kind==='spin'?`${r.amount} спин`:r.kind==='gift'?`Telegram-подарок ${r.amount} ⭐`:`${r.amount} ${r.kind}`}
function renderCases(items){$('cases').innerHTML=items.map((c,i)=>`<div class="case ${i===0?'featured':''}"><div class="case-icon">${c.icon}</div><div><div class="case-name">${c.title}</div><div class="case-desc">${c.free_price!==undefined?'Бесплатная попытка каждый день':'Больше Stars и редкий Telegram-подарок'}</div><div class="case-actions">${c.free_price!==undefined?`<button class="buy-btn free" onclick="openCase('${c.slug}','free')">ОТКРЫТЬ БЕСПЛАТНО</button>`:''}${c.key_price!==undefined?`<button class="buy-btn primary" onclick="openCase('${c.slug}','key')">🗝 ${c.key_price}</button>`:''}${c.stars_price!==undefined?`<button class="buy-btn" onclick="openCase('${c.slug}','stars')">⭐ ${c.stars_price}</button>`:''}</div></div></div>`).join('')}
async function reloadProfile(){const n=$('name');try{profile=await api('/api/game/profile');const u=profile.user;n.classList.remove('skeleton');n.textContent=u.name+(u.vip_until?' · 💎 VIP':'');$('avatar').textContent=(u.name.replace('@','')[0]||'S').toUpperCase();$('balance').textContent=u.balance+' ⭐';$('keys').textContent=u.keys+' 🗝';$('spins').textContent=u.spins+' 🎟';$('spinBadge').textContent=u.spins+' спинов';$('level').textContent='LVL '+u.level;$('levelFill').style.width=Math.min(100,(u.xp%100))+'%';renderCases(profile.cases)}catch(e){n.classList.remove('skeleton');n.textContent='Не удалось загрузить профиль';toast(e.message)}}
function confetti(){const colors=['#fbbf24','#ec4899','#8b5cf6','#22d3ee','#34d399'];for(let i=0;i<28;i++){let p=document.createElement('i');p.className='confetti';p.style.left=Math.random()*100+'vw';p.style.background=colors[i%colors.length];p.style.setProperty('--x',(Math.random()*180-90)+'px');p.style.animationDelay=Math.random()*.35+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),2300)}}
function showPrize(r){$('prizeIcon').textContent=r.kind==='gift'?'🎁':r.kind==='key'?'🗝':r.kind==='spin'?'🎟':'⭐';$('prizeTitle').textContent='Поздравляем!';$('prizeText').textContent=rewardLabel(r)+(r.status==='pending'?' · подарок ожидает выдачи':'');$('overlay').classList.add('show');confetti();haptic('success')}
function closePrize(){$('overlay').classList.remove('show')}
async function spinWheel(){const b=$('spinBtn');try{b.disabled=true;haptic();const j=await api('/api/game/spin',{requestId:requestId()});rotation+=1440+Math.floor(Math.random()*360);$('wheel').style.transform=`rotate(${rotation}deg)`;setTimeout(()=>showPrize(j.reward),3350);setTimeout(reloadProfile,3500)}catch(e){toast(e.message);b.disabled=false;return}setTimeout(()=>b.disabled=false,3550)}
async function openCase(c,p){if(gameBusy)return;gameBusy=true;try{haptic();const j=await api('/api/game/case',{case:c,payment:p,requestId:requestId()});showPrize(j.reward);await reloadProfile()}catch(e){toast(e.message)}finally{gameBusy=false}}
async function buy(product){try{haptic();const j=await api('/api/game/invoice',{product});if(!tg?.openInvoice)throw Error('Откройте приложение внутри Telegram');tg.openInvoice(j.invoice,status=>{if(status==='paid'){toast('✅ Покупка успешно оплачена');setTimeout(reloadProfile,900)}})}catch(e){toast(e.message)}}
function share(){const id=profile?.user?.id||'';const url='https://t.me/share/url?url='+encodeURIComponent('https://t.me/{username}?start=ref_'+id)+'&text='+encodeURIComponent('Зарабатывай Stars вместе со мной');tg?.openTelegramLink(url)}
reloadProfile();
</script></body></html>"""
